program: hyperparameter-tuning/tune_base.py
command:
- ${env}
- C:\Users\siena\repositories\thesis\multiconer\multiconer\Scripts\python.exe
- ${program}
- ${args}
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  epochs:
    value: 10
  batch_size:
    values: [8, 16]
  learning_rate:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  weight_decay:
    values: [0.0, 0.001, 0.01, 0.1]